---
title: "Representatividad y ajustes en encuestas electorales"
subtitle: "Máster en Análisis Político y Electoral"
author: "Pablo Cabrera Álvarez · pablocal@usal.es"
date: "Nov. 2011"
output: pdf_document
---
## Objetivos
Al concluir la sesión los estudiantes:

- Comprenderán los problemas generados por la falta de cobertura y la no-respuesta en encuestas.
- Serán capaces de desarrollar un análisis de representatividad básico.
- Comprenderán la lógica de los ajustes por ponderación.
- Diseñarán y generarán coeficientes de ponderación con `R`.

## Metodología
La sesión estará compuesta por dos módulos teoricos seguidos de dos actividades prácticas. En las práctica se usará `R` para analizar la representatividad de una muestra, que posteriormente será ajustada utilizando la técnica de calibración. 

En las dos prácticas los estudiantes tendrán una plantilla de *script* y una guía para realizar la actividad paso a paso. El *script* completo estará disponible.

En los ejercicios prácticos se utilizarán los microdatos de una encuesta preelectoral de GESOP de febrero de 2019, publicada en El Periódico.

## 1. Problemas de representatividad en las encuestas (30')
- **Encuestas y representatividad**. Explicar la lógica de la representatividad en la investigación con encuestas. Distinguir entre porblemas de cobertura y no-respuesta.
- **Tipos de muestras y potenciales problemas** aplicado a las encuestas electorales. Entender cómo los problemas de representatividad dan lugar a desviaciones de las estimaciones de voto. Utilizar casos históricos de *polling failure*. 
- **Análisis de representatividad** de las muestras e introducción a los *R-indicators*. Desarrollar un marco de evaluación para analizar el nivel de representatividad de una muestra. Introducir el uso de los *R-indicators*.

### Práctica 1: análisis de representatividad (40')
Analizar la representatividad de la encuesta de GESOP. Realizar un análisis por tablas de contingencia y comparar con los resultados de los *R-indicators*.

## 2. Ajustar las estimaciones con pesos (50')
- Aproximación a la **lógica de la ponderación**. Lógica de la ponderación. Relación entre las variables auxiliares, la variable objetivo y el mecanismo de respuesta. 
- **Tipos de ponderaciones**. Pesos de selección, representatividad y analíticos. El caso de las muestras no probabilísticas.
- **Técnicas** utilizadas para generar las ponderaciones. *Cell-weights*, pesos probabilísticos, calibración y postestratificación, *propensity score*, pesos a partir de modelos. 
- **Datos auxiliares**. Fuentes de datos auxiliares. Datos usuales en las encuestas sociopolíticas (INE(s), CIS, ESS).
- Generar **ponderaciones en `R`**. Introdución al paquete `survey` y a las funciones `svydesign` y `calibrate`.
- **Evaluar los pesos**. Efecto de los pesos en el diseño (*DEFF*). *Trim*, escalar y comparar con totales poblacionales. 

## Práctica 2: generación de ponderaciones por calibración (50')
Generar un conjunto de ponderaciones utilizando `calibrate`, la encuesta de GESOP y los datos poblacionales. Evaluar y ajustar la ponderación final.

## Bibliografía
Atkeson, L. R., & Alvarez, R. M. (Eds.). (2018). The Oxford Handbook of Polling and Survey Methods. Oxford University Press.

Bethlehem, J., & Cobben, F. (2013, August). Web Panels for Official Statistics?. In Proceedings 59th ISI World Statistics Congress (Vol. 25).

Bethlehem, J., Cobben, F., & Schouten, B. (2011). Handbook of nonresponse in household surveys (Vol. 568). John Wiley & Sons.

De Leeuw, E. D., Hox, J., & Dillman, D. (2012). International handbook of survey methodology. Routledge.

Elliott, M. R., & Valliant, R. (2017). Inference for nonprobability samples. Statistical Science, 32(2), 249-264.

Groves, R. M., Biemer, P. P., Lyberg, L. E., Massey, J. T., Nicholls, W. L., & Waksberg, J. (Eds.). (2001). Telephone survey methodology (Vol. 328). John Wiley & Sons.

Lee, S., & Valliant, R. (2009). Estimation for volunteer panel web surveys using propensity score adjustment and calibration adjustment. Sociological Methods & Research, 37(3), 319-343.

Leslie Kish. (1995). Survey sampling (Vol. 60). Wiley-Interscience.

Kohut, A., Keeter, S., Doherty, C., Dimock, M., & Christian, L. (2012). Assessing the representativeness of public opinion surveys. Washington, DC: Pew Research Center.

Park, D. K., Gelman, A., & Bafumi, J. (2004). Bayesian multilevel estimation with poststratification: State-level estimates from national polls. Political Analysis, 12(4), 375-385.

Särndal, C. E., & Lundström, S. (2005). Estimation in surveys with nonresponse. John Wiley & Sons.

Schouten, B., Bethlehem, J., Beullens, K., Kleven, Ø., Loosveldt, G., Luiten, A., ... & Skinner, C. (2012). Evaluating, comparing, monitoring, and improving representativeness of survey response through R‐indicators and partial R‐indicators. International Statistical Review, 80(3), 382-399.

Wang, W., Rothschild, D., Goel, S., & Gelman, A. (2015). Forecasting elections with non-representative polls. International Journal of Forecasting, 31(3), 980-991.

Sturgis, P., Nick, B., Mario, C., Stephen, F., Jane, G., Jennings, W., ... & Patten, S. (2016). Report of the inquiry into the 2015 British general election opinion polls.
