---
title: "Representatividad y ajustes en encuestas electorales"
subtitle: "Máster en Análisis Político y Electoral"
author: "Pablo Cabrera Álvarez · pablocal@usal.es"
date: "Nov. 2011"
output: pdf_document
---
## Objetivos
Al concluir la sesión los estudiantes:

- Comprenderán los problemas generados por la falta de cobertura y la no-respuesta.
- Diseñarán un análisis de representatividad básico.
- Entenderán la lógica de los ajustes por ponderación y su capacidad de mejorar la representatividad de la muestra.
- Diseñarán  y generarán coeficientes de ponderación.

## Metodología
La sesión tendrá dos actividades prácticas en las que utilizando R se realizará un análisis de representatividad de una encuesta, que posteriormente será ajustada utilizando la técnica de calibración. 

En las dos prácticas los estudiantes tendrán una plantilla de *script* y una guía para realizar la actividad paso a paso. El *script* correspondiente con los problemas resueltos también estarán disponibles. 

Para los ejercicios prácticos se utilizará los microdatos de una encuesta preelectoral de GESOP de febrero de 2019, publicada en El Periódico.

## 1. Problemas de representatividad en las encuestas (30')
- **Encuestas, otros datos y representatividad**. Explicar la lógica de la representatividad en la investigación con encuestas. Distinguir entre porblemas de cobertura y no-respuesta. Plantear el problema de la representatividad aplicado a otras fuentes de datos más allá de las encuestas.
- **Tipos de muestras y potenciales problemas** aplicado a las encuestas electorales. Entender cómo los problemas de representatividad dan lugar a desvíos de las encuestas electorales. Utilizar casos históricos de *polling failure*. 
- **Análisis de representatividad** de las muestras e introducción a los *R-indicators*. Desarrollar un marco de evaluación para analizar el nivel de representatividad de una muestra. Introducir el uso de los *R-indicators*.

### Práctica 1: análisis de representatividad (40')
Analizar la representatividad de la encuesta de GESOP. Realizar un análisis por tablas de contingencia y comparar con los resultados de los *R-indicators*.

## 2. Ajustar las estimaciones con pesos (50')
- Aproximación a la **lógica de la ponderación**. Lógica de la ponderación. Relación entre las variables auxiliares, la variable objetivo y el mecanismo de respuesta. 
- **Tipos de ponderaciones**. Pesos de selección, representatividad y analíticos.
- **Técnicas** utilizadas para generar las ponderaciones. *Cell-weights*, pesos probabilísticos, calibración y postestratificación, *propensity score*, pesos de modelo. 
- **Datos auxiliares**. Fuentes de datos auxiliares. Datos usuales en las encuestas sociopolíticas (INE(s), CIS, ESS).
- Generar **ponderaciones en `R`**. Introdución al paquete `survey` y al comando `svydesign` y `calibrate`.
- Evaluar los **coeficientes de ponderación**. Efecto de los pesos en el diseño (*DEFF*). *Trim*, escalar y comparar con totales poblacionales. 

## Práctica 2: generación de ponderaciones por calibración (50')
Generar un conjunto de ponderaciones utilizando calibración utilizando `calibrate`, la encuesta de GESOP y los datos poblacionales. Evaluar y ajustar la ponderación final.

## Bibliografía

Elliott, M. R., & Valliant, R. (2017). Inference for nonprobability samples. Statistical Science, 32(2), 249-264.

Groves, R. M., Biemer, P. P., Lyberg, L. E., Massey, J. T., Nicholls, W. L., & Waksberg, J. (Eds.). (2001). Telephone survey methodology (Vol. 328). John Wiley & Sons.

Kohut, A., Keeter, S., Doherty, C., Dimock, M., & Christian, L. (2012). Assessing the representativeness of public opinion surveys. Washington, DC: Pew Research Center.

Schouten, B., Bethlehem, J., Beullens, K., Kleven, Ø., Loosveldt, G., Luiten, A., ... & Skinner, C. (2012). Evaluating, comparing, monitoring, and improving representativeness of survey response through R‐indicators and partial R‐indicators. International Statistical Review, 80(3), 382-399.

Sturgis, P., Nick, B., Mario, C., Stephen, F., Jane, G., Jennings, W., ... & Patten, S. (2016). Report of the inquiry into the 2015 British general election opinion polls.
